version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: e_commerce
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e_commerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/init-db.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/e_commerce_db?charSet=UTF-8
      SPRING_DATASOURCE_USERNAME: e_commerce
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
        - db
    ports:
        - "${APP_PORT:-8080}:8080"